// Friendly aliases used across apps. Keep this stable even when database.types.ts
// is regenerated by `supabase gen types`.
export type {
  Json,
  Domain,
  EntryStatus,
  DefaultView,
  TypeStatus,
  TypeDefinitionRow,
  EntryRow,
  TagRow,
} from './database.types'

import type { TypeDefinitionRow, EntryRow, TagRow } from './database.types'

/** A single filed piece of content. */
export type Entry = EntryRow

/** A category definition — doubles as the LLM classification rulebook and the
 *  frontend's schema-driven form spec. */
export type TypeDefinition = TypeDefinitionRow

export type Tag = TagRow

/** An attrs_schema field descriptor, e.g. "string" or "enum:$/$$/$$$". */
export interface AttrFieldSpec {
  kind: 'string' | 'enum'
  options?: string[]
}

/** Parse an attrs_schema value into a normalised field spec for form rendering. */
export function parseAttrField(raw: unknown): AttrFieldSpec {
  if (typeof raw === 'string' && raw.startsWith('enum:')) {
    return { kind: 'enum', options: raw.slice('enum:'.length).split('/').filter(Boolean) }
  }
  return { kind: 'string' }
}
